spring:
  sql:
    init:
      mode: always
  application:
    name: General
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
  jackson:
    time-zone: America/Fortaleza
server:
  port: 8081

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

tokens:
  expiration:
    access:
      exp: ${ACCESS_T}
    refresh:
      exp: ${REFRESH_T}

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG # Exibe informações sobre a execução dos scripts
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG # Pode dar pistas sobre a inicialização do JPA
    org.hibernate.SQL: DEBUG # Você já tem este, mas é bom para ver o DDL